#  NumPy

- **[1.1 NumPy の概観](#1.1-NumPyの概観)**
    - **[1.1.1 NumPyとは](#1.1.1-NumPyとは)**
    - **[1.1.2 NumPyの高速な処理の体験](#1.1.2-NumPyの高速な処理の体験)**
<br><br>
- **[1.2 NumPy 1次元配列](#1.2-NumPy-1次元配列)**
    - **[1.2.1 import](#1.2.1-import)**
    - **[1.2.2 1次元配列](#1.2.2-1次元配列)**
    - **[1.2.3 1次元配列の計算](#1.2.3-1次元配列の計算)**
    - **[1.2.4 インデックス参照とスライス](#1.2.4-インデックス参照とスライス)**
    - **[1.2.5 ndarrayの注意点](#1.2.5-ndarrayの注意点)**
    - **[1.2.6 viewとcopy](#1.2.6-viewとcopy)**
    - **[1.2.7 ブールインデックス参照](#1.2.7-ブールインデックス参照)** 
    - **[1.2.8 ユニバーサル関数](#1.2.8-ユニバーサル関数)**
    - **[1.2.9 集合関数](#1.2.9-集合関数)**  
    - **[1.2.10 乱数](#1.2.10-乱数)**
<br><br>
- **[1.3 NumPy 2次元配列](#1.3-NumPy-2次元配列)**
    - **[1.3.1 2次元配列](#1.3.1-2次元配列)**
    - **[1.3.2 インデックス参照とスライス](#1.3.2-インデックス参照とスライス)**
    - **[1.3.3 axis](#1.3.3-axis)**
    - **[1.3.4 ファンシーインデックス参照](#1.3.4-ファンシーインデックス参照)**
    - **[1.3.5 転置行列](#1.3.5-転置行列)**
    - **[1.3.6 ソート](#1.3.6-ソート)**
    - **[1.3.7 行列計算](#1.3.7-行列計算)**
    - **[1.3.8 数学関数](#1.3.8-数学関数)**
    - **[1.3.9 ブロードキャスト](#1.3.9-ブロードキャスト)**
<br><br>
- **[1.3 添削問題](#1.3-添削問題)**

 ***

## 1.1 NumPy の概観

### 1.1.1 NumPyとは

**<font color=#AA0000>NumPy</font>** とは、Pythonでベクトルや行列計算を高速に行うのに特化した基盤となるライブラリです。 **ライブラリとは外部から読み込むPythonのコードの塊** です。ライブラリの利点は、本来長いコードを書くところを短く書ける点、処理速度が早くなる（場合がある）点です。Pythonが機械学習分野で広く活用されている理由には、NumPyを始めとする科学技術計算に便利なライブラリの充実が挙げられます。ライブラリのなかには、たくさんのモジュールが入っており、モジュールはたくさんの関数でまとまっていると押さえておけば良いでしょう。

例: Numpyライブラリ > Numpy.randomモジュール > randint()関数

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/img1_10.png" width="500">

 　Pythonで他に利用されるライブラリには、 **Scipy** 、 **Pandas** 、 **scikit-learn** 、 **Matplotlib** などがあります。これらのライブラリや開発環境などを含めたPythonの環境全体を指して**エコシステム**と呼ばれます。以下の図はPythonのエコシステムの概観を表しています。下にあるほど基盤となるような機能を提供します。NumPyは他のライブラリにも関係する、非常に基礎的な役割を担っているのです。

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/img1_20.png" width="500">

#### 問題


- NumPyは以下の選択肢のうち、どの処理を行うライブラリですか。

- データのプロットを行う。
- 独自のデータ構造を使い、データを操作する。
- 機械学習のライブラリを提供する。
- ベクトルや行列計算を高速化する。

#### ヒント

- NumPyはベクトルや行列計算に特化しています。

#### 解答例

ベクトルや行列計算を高速化する。

***

### 1.1.2 NumPyの高速な処理の体験

Pythonはベクトルや行列計算の処理が低速で、それを補うライブラリとしてNumPyが存在することを説明しました。次の行列の計算を実行して、NumPyにより処理が高速化されていることを確認しましょう。

詳しいコードの内容は、次の節から説明するので、今回はこちらのコードを実行して、NumPyの行列計算の速度を見てみるだけでOKです。

#### 問題


- 次の行列計算を実行して、NumPyにより処理が高速化されていることを確認しましょう。

In [ ]:
# 必要なライブラリをimport
import numpy as np
import time
from numpy.random import rand

# 行、列の大きさ
N = 150

# 行列の初期化
matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

# Pythonのリストを使って計算

# 開始時間の取得
start = time.time()

# for文を使って行列の掛け算を実行
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("Pythonの機能のみでの計算結果：%.2f[sec]" % float(time.time() - start))

# NumPyを使って計算

# 開始時間の取得
start = time.time()

# NumPyを使って行列の掛け算を実行
matC = np.dot(matA, matB)

# 少数第2位の桁で打ち切っているのでNumPyは0.00[sec]と表示されます。
print("NumPyを使った場合の計算結果：%.2f[sec]" % float(time.time() - start))

#### ヒント

- 桁は第2位で打ち切っているのでNumPyは0.00[sec]と表示されますが、0ではありません。

#### 解答例

In [ ]:
# 必要なライブラリをimport
import numpy as np
import time
from numpy.random import rand

# 行、列の大きさ
N = 150

# 行列の初期化
matA = np.array(rand(N, N))
matB = np.array(rand(N, N))
matC = np.array([[0] * N for _ in range(N)])

# Pythonのリストを使って計算

# 開始時間の取得
start = time.time()

# for文を使って行列の掛け算を実行
for i in range(N):
    for j in range(N):
        for k in range(N):
            matC[i][j] = matA[i][k] * matB[k][j]

print("Pythonの機能のみでの計算結果：%.2f[sec]" % float(time.time() - start))

# NumPyを使って計算

# 開始時間の取得
start = time.time()

# NumPyを使って行列の掛け算を実行
matC = np.dot(matA, matB)

# 少数第2位の桁で打ち切っているのでNumPyは0.00[sec]と表示されます。
print("NumPyを使った場合の計算結果：%.2f[sec]" % float(time.time() - start))

***

## 1.2 NumPy 1次元配列

### 1.2.1 import

さて、このセクションから本格的にNumPyを使ったプログラミングに挑戦します。

NumPyを`import`するときは`import numpy`と表記します。読み込んだNumPyを用いるには`numpy.モジュール名`という形で用います。`import numpy as np`のように`as`を用いて`import _____ as __`と表記するとパッケージ名を変更することができ、`np.モジュール名`の形で用いることができます。
Pythonコミュニティーには、慣習としてよく使われるモジュールの命名規則があり、`numpy`は`np`という名前で定義されます。(以下、この教材でも`numpy`は`np`として表記していきます。)

#### 問題


- NumPyを`import`し、`np`という名前で定義してください。

In [ ]:
# NumPyをimportしてください



#### ヒント

- `import _____ as __`

#### 解答例

In [ ]:
# NumPyをimportしてください
import numpy as np


***

### 1.2.2 1次元配列

NumPyには配列を高速に扱うための`ndarray`クラスが用意されています。`ndarray`を生成する方法の一つは、NumPyの`np.array`関数を用いる方法です。 **`np.array(リスト)`と表記し、リストを与えることで作成** します。<br>
`np.array([1,2,3])`

また、`np.arange`関数を用いる方法があり、`np.arange(X)`と表記し等間隔に増減させた値の要素をX個作成してくれます。<br>
`np.arange(4)  # 出力結果 [0 1 2 3]`

ndarrayクラスは一次元の場合はベクトル、二次元の場合は行列、三次元以上はテンソルと呼ばれます。テンソルについては数学的な概念ですが、機械学習では単に行列の概念を拡張したものと捉えて頂いて大丈夫です。一次元、二次元、三次元の`np.array`の例は以下のようになります。

一次元のndarrayクラス<br>
`array_1d = np.array([1,2,3,4,5,6,7,8])`

二次元のndarrayクラス<br>
`array_2d = np.array([[1,2,3,4],[5,6,7,8]])`

三次元のndarrayクラス<br>
`array_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])`

#### 問題


- 変数`storages`から`ndarray`配列を生成し、変数`np_storages`に代入してください。
- 変数`np_storages`の型を出力してください。

In [ ]:
import numpy as np

storages = [24, 3, 4, 23, 10, 12]
print(storages)

# ndarray配列を生成し、変数np_storagesに代入してください
np_storages = 
print(np_storages)

# 変数np_storagesの型を出力してください
print()


#### ヒント

- `np.array(リスト)`
- 型を出力する関数は`type(任意の変数など)`です。

#### 解答例

In [ ]:
import numpy as np

storages = [24, 3, 4, 23, 10, 12]
print(storages)

# ndarray配列を生成し、変数np_storagesに代入してください
np_storages = np.array(storages)
print(np_storages)

# 変数np_storagesの型を出力してください
print(type(np_storages))

***

### 1.2.3 1次元配列の計算

リストでは、要素ごとの計算を行うためには、 **ループを書いて要素を一つずつ取り出して足し算** を行う必要がありましたが、 **`ndarray`ではループで書く必要はありません。** `ndarray`同士の算術演算では、同じ位置にある要素同士で計算されます。


NumPyを使わない実行
```python
storages = [1, 2, 3, 4]
new_storages = []
for n in storages:
    n += n
    new_storages.append(n)
print(new_storages)

# 出力結果
[2 4 6 8]
```

NumPyを使う実行

```python
import numpy as np
storages = np.array([1, 2, 3, 4])
storages += storages
print(storages)

# 出力結果
[2 4 6 8]
```

#### 問題


- 変数`arr`同士を足したものを出力してください。
- 変数`arr`同士を引いたものを出力してください。
- 変数`arr`の3乗を出力してください。
- 1を変数`arr`で割った値を出力してください。
- 出力はprint関数を用いてください。

In [ ]:
import numpy as np

arr = np.array([2, 5, 3, 4, 8])

# arr + arr
print()

# arr - arr
print()

# arr ** 3
print()

# 1 / arr
print()


#### ヒント

- 変数の計算の時と同様にすれば良いです。

#### 解答例

In [ ]:
import numpy as np

arr = np.array([2, 5, 3, 4, 8])

# arr + arr
print('arr + arr')
print(arr + arr)
print()

# arr - arr
print('arr - arr')
print(arr - arr)
print()

# arr ** 3
print('arr ** 3')
print(arr ** 3)
print()

# 1 / arr
print('1 / arr')
print(1 / arr)
print()


***

### 1.2.4 インデックス参照とスライス

リスト型と同様にNumPyでも **インデックス参照やスライスをする** ことができます。インデックス参照はPython入門Chapter2[「**リストから値を取り出す**」](https://aidemy.net/courses/3010/exercises/ByDZYn8oLlz)で、スライスは同じくChapter2[「**リストからリストを取り出す**」](https://aidemy.net/courses/3010/exercises/By_WF3IsLlf)で確認しましたね。インデックス参照とスライスの方法はリストの時と同じ方法です。1次元配列はベクトルであるので、インデックスで参照した先はスカラー値（通常の整数や小数点など）となります。

スライスの値を変更したいときは`arr[start:end] = 変更したい値`と表記します。なお、 **arr[start:end]の時、startから<font color=#AA0000>(end-1)まで</font>のリスト** が作成されることに注意してください。


```python
arr = np.arange(10)
print(arr)
# 出力結果
[0 1 2 3 4 5 6 7 8 9]
```
```python
arr = np.arange(10)
arr[0:3] = 1
print(arr)
# 出力結果
[1 1 1 3 4 5 6 7 8 9]
```

#### 問題


- 変数`arr`の要素の内`3, 4, 5`だけを出力してください。
- 変数`arr`の要素の内`3, 4, 5`を24に変更してください。

In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)

# 変数arrの要素の内3, 4, 5だけを出力してください
print()

# 変数arrの要素の内3, 4, 5を24に変更してください

print(arr)

#### ヒント

- `arr[start:end]`の時、`start`から`(end-1)`までのリストが作成されます。
- `arr[start:end] = 変更したい値`

#### 解答例

In [ ]:
import numpy as np

arr = np.arange(10)
print(arr)

# 変数arrの要素の内3, 4, 5だけを出力してください
print(arr[3:6])

# 変数arrの要素の内3, 4, 5を24に変更してください
arr[3:6] = 24
print(arr)

***

### 1.2.5 ndarrayの注意点

ndarrayはpythonのリストと同じように **代入先の変数の値を変更すると元のndarray配列の値も変更** されます。そのため、 **ndarrayをコピーして2つの別々の変数にしたい時は、`copy( )`メソッドを使用** します。このメソッドは`コピーしたい配列.copy()`で使用できます。

#### 問題


- 次のコードを実行して、挙動を確認しましょう。

In [ ]:
import numpy as np

# ndarrayをそのまま別の変数に代入した場合の挙動を見て行きましょう。
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

# 別の変数への変更が元の変数にも影響されています。
print(arr1)

# ndarrayをcopy( )を使って別の変数に代入した場合の挙動を見て行きましょう。
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

# 別の変数への変更が元の変数には影響を与えていません。
print(arr1)

#### ヒント

- ある変数をそのまま別の変数に代入すると元の変数のデータの場所が代入され、結果的に元のデータと同じものとなっていることに注意してください。

#### 解答例

In [ ]:
import numpy as np

# ndarrayをそのまま別の変数に代入した場合の挙動を見て行きましょう。
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1
arr2[0] = 100

# 別の変数への変更が元の変数にも影響されています。
print(arr1)

# ndarrayをcopy( )を使って別の変数に代入した場合の挙動を見て行きましょう。
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = arr1.copy()
arr2[0] = 100

# 別の変数への変更が元の変数には影響を与えていません。
print(arr1)

***

### 1.2.6 viewとcopy

Pythonのリストとndarrayの相違点としては、`ndarray`のスライスは配列のコピーではなく **<font color=#AA0000>view</font>** であることです。 **viewとは、もとの配列と同じデータを指している** ことを指します。つまり`ndarray`のスライスの変更は、オリジナルの`ndarray`を変更するということになります。前節で確認した通り、スライスを **コピーとして扱いたい場合には`arr[:].copy()`** とします。

#### 問題


- 次の処理を実行して、PythonのリストとNumPyのndarrayのスライスを行った時の挙動の違いを確認してくだい。

In [ ]:
import numpy as np

# Pythonのリストでスライスを用いた場合の挙動を確認しましょう。
arr_List = [x for x in range(10)]
print("リスト型データです")
print("arr_List:",arr_List)

print()
arr_List_copy = arr_List[:]
arr_List_copy[0] = 100

# リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません。
print("リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません。")
print("arr_List:",arr_List)
print()
print('-----------------------------------------------------------------------------------')
# NumPyのndarrayでスライスを用いた場合での挙動を確認しましょう。
arr_NumPy = np.arange(10)
print("NumPyのndarrayデータです")
print("arr_NumPy:",arr_NumPy)
print()

arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100

# NumPyのスライスではビュー(データが格納されている場所の情報)が代入されるので
# arr_NumPy_viewの変更がarr_NumPyに反映されます。
print("NumPyのスライスではビュー(データが格納されている場所の情報)が代入されるので、arr_NumPy_viewの変更がarr_NumPyに反映されます。")
print("arr_NumPy:",arr_NumPy)
print()
# NumPyのndarrayでcopy()を用いた場合での挙動を確認しましょう。
arr_NumPy = np.arange(10)
print('NumPyのndarrayでcopy()を用いた場合での挙動です')
print("arr_NumPy:",arr_NumPy)
print()
arr_NumPy_copy = arr_NumPy[:].copy()
arr_NumPy_copy[0] = 100

# copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません。
print("copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません。")
print("arr_NumPy:",arr_NumPy)

#### ヒント

- PythonのリストとNumPyのndarrayはスライスを使った時の挙動が違うので注意しましょう。

In [ ]:
import numpy as np

# Pythonのリストでスライスを用いた場合の挙動を確認しましょう。
arr_List = [x for x in range(10)]
print("リスト型データです")
print("arr_List:",arr_List)

print()
arr_List_copy = arr_List[:]
arr_List_copy[0] = 100

# リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません。
print("リストのスライスではコピーが作られるので、arr_Listにはarr_List_copyの変更が反映されません。")
print("arr_List:",arr_List)
print()
print('-----------------------------------------------------------------------------------')
# NumPyのndarrayでスライスを用いた場合での挙動を確認しましょう。
arr_NumPy = np.arange(10)
print("NumPyのndarrayデータです")
print("arr_NumPy:",arr_NumPy)
print()

arr_NumPy_view = arr_NumPy[:]
arr_NumPy_view[0] = 100

# NumPyのスライスではビュー(データが格納されている場所の情報)が代入されるので
# arr_NumPy_viewの変更がarr_NumPyに反映されます。
print("NumPyのスライスではビュー(データが格納されている場所の情報)が代入されるので、arr_NumPy_viewの変更がarr_NumPyに反映されます。")
print("arr_NumPy:",arr_NumPy)
print()
# NumPyのndarrayでcopy()を用いた場合での挙動を確認しましょう。
arr_NumPy = np.arange(10)
print('NumPyのndarrayでcopy()を用いた場合での挙動です')
print("arr_NumPy:",arr_NumPy)
print()
arr_NumPy_copy = arr_NumPy[:].copy()
arr_NumPy_copy[0] = 100

# copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません。
print("copy()を用いた場合は、コピーが生成されているのでarr_NumPy_copyはarr_NumPyに影響を与えません。")
print("arr_NumPy:",arr_NumPy)

#### 解答例

***

### 1.2.7 ブールインデックス参照

**<font color=#AA0000>ブールインデックス参照</font>** とは、`[]`の中に **論理値(`True/False`)の配列を用いて要素を取り出す方法のこと** です。`arr[ndarrayの論理値の配列]`と表記すると、論理値配列の`True`に該当する箇所の要素の`ndarray`を作成して返してくれます。


```python 
arr = np.array([2, 4, 6, 7]) 
print(arr[np.array([True, True, True, False])])  
# 出力結果
[2 4 6]
```

これを応用すると、以下のようにndarrayの要素を抽出することができます。
以下のコードでは、3で割った時の余りが1の要素をTrueとして返し、3で割った時の余りの要素を出力しています。

```python 
arr = np.array([2, 4, 6, 7]) 
print(arr[arr % 3 == 1])
# 出力結果 
[4 7]
```

#### 問題


- 変数arrの各要素が2で割り切れるかどうかを示す真偽値の配列を出力してください。
- 変数arr各要素のうち2で割り切れる要素の配列を出力してください。

In [ ]:
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7])

# 変数arrの各要素が2で割り切れるかどうかを示す真偽値の配列を出力してください
print()

# 変数arr各要素のうち2で割り切れる要素の配列を出力してください
print()

#### ヒント

- 2で割り切れるかどうかは`arr % 2 == 0`で表せます。
- 真偽値の配列の出力は`print(条件)`で表せます。
- 要素の配列は`arr[ndarrayの論理値の配列]`で表せます。

#### 解答例

In [ ]:
import numpy as np

arr = np.array([2, 3, 4, 5, 6, 7])

# 変数arrの各要素が2で割り切れるかどうかを示す真偽値の配列を出力してください
print(arr % 2 == 0)

# 変数arr各要素のうち2で割り切れる要素の配列を出力してください
print(arr[arr % 2 == 0])

***

### 1.2.8 ユニバーサル関数

**<font color=#AA0000>ユニバーサル関数</font>** とは **`ndarray`配列の各要素に対して演算した結果を返す関数** のことです。要素ごとの計算なので多次元配列でも用いることができます。ユニバーサル関数には引数が一つのものと二つのものがあります。

引数が一つのものの代表例が、要素の絶対値を返す`np.abs()`関数、要素のe（自然対数の底）のべき乗を返す`np.exp()`関数や要素の平方根を返す`np.sqrt()`関数などです。

引数が二つのものの代表例が、要素同士の和を返す`np.add()`関数、要素同士の差を返す`np.subtract()`関数や要素同士の最大値を格納した配列を返す`np.maximum()`関数などがあります。

#### 問題


- 変数arrの各要素を絶対値にし、変数arr_absに代入してください。
- 変数arr_absの各要素のeのべき乗と平方根を出力してください。

In [ ]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# 変数arrの各要素を絶対値にし、変数arr_absに代入してください
arr_abs = 
print(arr_abs)

# 変数arr_absの各要素のeのべき乗と平方根を出力してください
print()
print()

#### ヒント

- それぞれの関数に「`np.`」をつけるのを忘れないようにしましょう。

#### 解答例

In [ ]:
import numpy as np

arr = np.array([4, -9, 16, -4, 20])
print(arr)

# 変数arrの各要素を絶対値にし、変数arr_absに代入してください
arr_abs = np.abs(arr)
print(arr_abs)

# 変数arr_absの各要素のeのべき乗と平方根を出力してください
print(np.exp(arr_abs))
print(np.sqrt(arr_abs))

***

### 1.2.9 集合関数

**<font color=#AA0000>集合関数</font>** とは **数学の集合演算を行う関数** のことです。 **1次元配列のみ** を対象としています。

代表的な関数は、配列要素から **重複を取り除きソートした結果を返す`np.unique()`関数** 、配列xとyのうち **少なくとも一方に存在する要素を取り出しソートする`np.union1d(x, y)`関数（和集合）** 、配列xとyのうち **共通する要素を取り出しソートする`np.intersect1d(x, y)`関数（積集合）** や **配列xと配列yに共通する要素を配列xから取り除きソートする`np.setdiff1d(x, y)`関数（差集合）** などがあります。



#### 問題


- `unique()`関数を用いて、変数arr1の重複をなくした配列を変数`new_arr1`に代入してください。
- 変数`new_arr1`と変数`arr2`の和集合を出力してください。
- 変数`new_arr1`と変数`arr2`の積集合を出力してください。
- 変数`new_arr1`から変数`arr2`を引いた差集合を出力してください

In [ ]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# unique()関数を用いて重複をなくした配列を変数new_arr1に代入してください
new_arr1 = 
print(new_arr1)

# 変数new_arr1と変数arr2の和集合を出力してください
print()

# 変数new_arr1と変数arr2の積集合を出力してください
print()

# 変数new_arr1から変数arr2を引いた差集合を出力してください
print()

#### ヒント

- それぞれの関数に「np.」をつけるのを忘れないようにしましょう。
- （※今回紹介した関数に使用されている文字はアルファベットのｌではなく数字の１です。）


#### 解答例

In [ ]:
import numpy as np

arr1 = [2, 5, 7, 9, 5, 2]
arr2 = [2, 5, 8, 3, 1]

# unique()関数を用いて重複をなくした配列を変数new_arr1に代入してください
new_arr1 = np.unique(arr1)
print(new_arr1)

# 変数new_arr1と変数arr2の和集合を出力してください
print(np.union1d(new_arr1, arr2))

# 変数new_arr1と変数arr2の積集合を出力してください
print(np.intersect1d(new_arr1, arr2))

# 変数new_arr1から変数arr2を引いた差集合を出力してください
print(np.setdiff1d(new_arr1, arr2))

***

### 1.2.10 乱数

NumPyでは`np.random`モジュールで乱数を生成することができます。代表的な`np.random`関数には、 **0以上1未満の一様乱数を生成する`np.random.rand()`関数、x以上y未満の整数をz個生成する`np.random.randint(x, y, z)`関数やガウス分布に従う乱数を生成する`np.random.normal()`関数** などがあります。

`np.random.rand()`関数は、 **()の中に整数を入れることで、その中にいれた整数の数分の乱数** が生成されます。

`np.random.randint(x, y, z)`関数は、 **x以上y<font color=#AA0000>未満</font>の整数** を生成することに注意しましょう。さらに、zには **`(2,3)`なども引数に入れることができ、そうすることで2×3の行列を生成** することができます。

通常これらの関数を用いる時、`np.random.randint()`としますが、何回も`np.random`を打つのは面倒だと思います。そこで`from numpy.random import randint`と最初に記述しておくと`randint()`のみで用いることができるようになります。これは、 **`「from モジュール名 import そのモジュールの中にある関数名」`** と一般化することができます。

#### 問題


- `randint()`関数をnp.randomとつけなくてもいいようにimportしてください。
- 変数`arr1`に各要素が0以上10以内の整数の行列`(5 × 2)`を代入してください。
- 0以上1未満の一様乱数を三つ生成し、変数`arr2`に代入してください。

In [ ]:
import numpy as np

# randint関数をnp.randomとつけなくてもいいようにimportしてください


# 変数arr1に、各要素が0 ~ 10まで整数の行列(5 × 2)を代入してください
arr1 = 
print(arr1)

# 変数arr2に0~1までの一様乱数を三つ代入してください
arr2 = 
print(arr2)

#### ヒント

- `import`する際は`np.random`ではなく、`numpy.random`です。
- `randint(x, y, z)`関数のzの値には`(1, 3)`なども引数として与えることができます。
- `randint(x, y, z)`関数はx以上y未満の整数を生成することに注意しましょう。


#### 解答例

In [ ]:
import numpy as np

# randint関数をnp.randomとつけなくてもいいようにimportしてください
from numpy.random import randint

# 変数arr1に、各要素が0 ~ 10まで整数の行列(5 × 2)を代入してください
arr1 = randint(0, 11, (5, 2))
print(arr1)

# 変数arr2に0~1までの一様乱数を三つ代入してください
arr2 = np.random.rand(3)
print(arr2)

***

## 1.3 NumPy 2次元配列

### 1.3.1 2次元配列

セクション「1次元配列」で述べたように2次元配列は、行列に該当します。`np.array([リスト, リスト])`と表記することで2次元配列を作成することができます。

`ndarray配列`の内部には`shape`という変数があり、`ndarray配列.shape`で各次元ごとの要素数を返すことができます。`ndarray配列.reshape(a,b)`で指定した引数と同じ形の行列に変換されます。ndarrayの変数を入れずに、ndarray配列そのものを入れても同じように返します。

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/img1_30.png" width="500">

#### 問題


- 変数`arr`にリスト`[[1, 2, 3, 4], [5, 6, 7, 8]]`を二次元配列に変換したものを代入してください。
- 変数`arr`の行列の各次元ごとの要素数をprint関数で出力してください。
- 変数`arr`を4行2列の行列に変換してください。

In [ ]:
import numpy as np

# 変数arrに二次元配列を代入してください
arr = 
print(arr)

# 変数arrの行列の各次元ごとの要素数を出力してください
print()

# 変数arrを4行2列の行列に変換してください
print()

#### ヒント

- `arr.reshape(x, y)`はxが行を表し、yが列を表します。

#### 解答例

In [ ]:
import numpy as np

# 変数arrに二次元配列を代入してください
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

# 変数arrの行列の各次元ごとの要素数を出力してください
print(arr.shape)

# 変数arrを4行2列の行列に変換してください
print(arr.reshape(4, 2))

***

### 1.3.2 インデックス参照とスライス

2次元配列の場合、インデックスを1つしか指定しない場合、任意の行が配列で取得できます。
```python
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1])
# 出力結果
[4 5 6]
```

個々の要素つまりスカラー値にたどり着くには、インデックスを2つ指定する必要があります。つまり、`arr[1][2]`または`arr[1, 2]`のようにアクセスする必要があります。`arr[1][2]`は`arr[1]`で取り出した配列の3番目の要素にアクセスしており、`arr[1, 2]`では二次元配列の軸をそれぞれ指定して要素にアクセスしています。
```python
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1,2])
# 出力結果
6
```

2次元配列を参照する時にスライスを利用することも可能です。スライスはPython入門Chapter2「 **リストからリストを取り出す** 」で確認しましたね。スライスを使う場合、以下のように指定すればOKです。以下の場合、「1行目」「1列目以降」を取り出す操作をしています。
```python
arr = np.array([[1, 2 ,3], [4, 5, 6]])
print(arr[1,1:])
# 出力結果
[5 6]
```

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/img1_40.png" width="300">

#### 問題


- 2次元配列 arr $
  \left[
    \begin{array}{rr}
     1 & 2 & 3 \\
     4 & 5 & 6 \\
     7 & 8 & 9
    \end{array}
  \right]
$を考えます。
- 変数`arr`の要素のうち3を出力してください。
- 変数`arr`から以下を部分的に取り出し出力してください。
```python
[[4 5]
 [7 8]]
```

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# 変数arrの要素のうち3を出力してください
print()

# 変数arrから取り出し出力してください
print()

#### ヒント

- 「`:`」をうまく用いてください。
- 「1行目以降」を取り出すには`1:`、「２列目まで」を取り出すには`:2`のように指定します。

#### 解答例

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

# 変数arrの要素のうち3を出力してください
print(arr[0, 2])

# 変数arrから取り出し出力してください
# 以下では、「1行目以降」と「２列目まで」を取り出しています
print(arr[1:, :2])

***

### 1.3.3 axis

2次元配列からは`axis`という概念が重要になってきます。 **`axis`とは座標軸** のようなものです。NumPyの関数の引数として`axis`を設定できる場面が多々あります。二次元配列の場合以下の図のように`axis`が設定されています。 **列ごとに処理を行う軸が`axis = 0`で、行ごとに処理を行う軸が`axis = 1`** ということになります。

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/numpy_axis.png" width="300">


例えば、`ndarray配列`の`sum()`メソッドを考えてみましょう。`ndarray.sum()`で **要素を足し合わせる** ことが出来ます。

```python
arr = np.array([[1, 2 ,3], [4, 5, 6]])

print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))
# 出力結果
21
[5 7 9]
[ 6 15]
```

このように、メソッド`sum()`の **引数に何も指定しない場合は、単純な合計値がスカラー（整数や小数など）** で、`sum()`の **引数に`axis=0`を指定した場合は縦に足し算が行われて要素が3つの1次元配列** に、`sum()`の **引数に`axis=1`を指定した場合は横に足し算が行われて要素が2つの1次元配列** になることが分かります。

#### 問題


- arrの行の合計値を求め、以下のような1次元配列を返してください。
```python
[ 6 21 57]
```

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])

# arrの行の合計値を求め、問題文の1次元配列を返してください
print()

#### ヒント

- メソッド`.sum()`を使います。
- 行を残して、列ごとに処理をする必要があるので、軸の設定は`axis=1`となります。

#### 解答例

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 12], [15, 20, 22]])

# arrの行の合計値を求め、問題文の1次元配列を返してください
print(arr.sum(axis=1))

***

### 1.3.4 ファンシーインデックス参照

**<font color=#AA0000>ファンシーインデックス参照</font>** とは、インデックス参照にインデックスの配列を用いる方法のことです。ある`ndarray`配列から **ある特定の順序で行を抽出** するには、 **その順番を示す配列** をインデックス参照として渡せばいいです。

スライスとは異なり、ファンシーインデックス参照は常に元データのコピーを返し、新しい要素を作成します。


```python
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]]) 

# 3行目、2行目、0行目の順番に行の要素を抽出し、新しい要素を作成します。
# インデックス番号は0から始まります。
print(arr[[3, 2, 0]]) 
# 出力結果
[[7 8]
 [5 6]
 [1 2]]
```


#### 問題


- ファンシーインデックス参照を用いて、変数`arr`の2行目, 4行目, 1行目の順番で配列を出力してください。なお、 **ここで言う行は<font color=#AA0000>インデックス番号とは異なり、1行目から数える行</font>** のことを言います。

In [ ]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

# 変数arrの行の順番を変更したものを出力してください
print()

#### ヒント

- `arr[3, 2, 0]`ではなく、`arr[[3, 2, 0]]`であることに注意しましょう。
- インデックス番号は0番目からです。

#### 解答例

In [ ]:
import numpy as np

arr = np.arange(25).reshape(5, 5)

# 変数arrの行の順番を変更したものを出力してください
print(arr[[1, 3, 0]])

***

### 1.3.5 転置行列

行列では、 **行と列を入れ替えることを<font color=#AA0000>転置</font>** と言います。転置行列は、行列の内積の計算などで出て来ることもあります。`ndarray`を転置するには、`np.transpose()`関数を用いる方法と`.T`を用いる方法の二つあります。

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/img1_50.png" width="500">

#### 問題


- 変数`arr`を転置させ、出力してください。

In [ ]:
import numpy as np

arr = np.arange(10).reshape(2, 5)

# 変数arrを転置させてください
print()

#### ヒント

- `transpose()`関数を用いる場合は、`np.`を忘れないようにしてください。
- `arr.T`を用いても転置を行うことができます。

#### 解答例

In [ ]:
import numpy as np

arr = np.arange(10).reshape(2, 5)

# 変数arrを転置させてください
print(arr.T) # print(np.transpose(arr))

***

### 1.3.6 ソート

`ndarray`もリスト型と同様に`sort()`メソッドでソートすることが可能です。2次元配列の場合、 **0を引数とすると列単位で要素がソートされ、1を引数にすると行単位で要素がソート** されます。なお、`np.sort()`関数でもソートをすることができます。`sort()`メソッドと異なる点は、 **`np.sort()`関数はソートした配列のコピーを返す関数** である点です。

また、実際に機械学習を学んでいく上でよく使われる関数に`argsort()`メソッドというものがあります。`argsort()`メソッドは **ソート後の配列のインデックス** を返します。




```python
arr = np.array([15, 30, 5])
arr.argsort()
# 出力結果 
[2 0 1]
```

以上の例の場合、`arr.sort()`すると、`[5 15 30]`となるので、もとの配列で **「2番目」にあった要素「5」** が0番目、もとの配列で **「0番目」にあった要素「15」** が1番目、もとの配列で **「1番目」にあった要素「30」** が2番目の要素になります。そのため、`[15, 30, 5]`を`.argsort() `すると、順に「2番目、0番目、1番目」の要素になるということで、 `[2 0 1]`と値が返されるのです。

#### 問題


- 変数`arr`を`argsort`関数でソートし出力してください。
- 変数`arr`を`np.sort()`でソートし出力してください。
- 変数`arr`を`sort()`により行でソートしてください。

In [ ]:
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

# argsort関数を用いて出力してください
print()

# np.sort()を用いてソートし出力してください
print()

# sort()を用いて行でソートしてください

print(arr)

#### ヒント

- 列でソートする場合は引数を0、行でソートする場合は引数を1とします。

#### 解答例

In [ ]:
import numpy as np

arr = np.array([[8, 4, 2], [3, 5, 1]])

# argsort関数を用いて出力してください
print(arr.argsort())

# np.sort()を用いてソートし出力してください
print(np.sort(arr))

# sort()を用いて行でソートしてください
arr.sort(1)
print(arr)

***

### 1.3.7 行列計算

行列計算をするための関数には、二つの行列の行列積を返す`np.dot(a,b)`関数やノルムを返す`np.linalg.norm(a)`関数などがあります。

行列積とは、行列の中にある行ベクトルと列ベクトルとの内積を要素とする行列が新たに作り出されることです。行列計算に関しては今回は深く触れませんが、以下のように計算することができます。
`np.dot(a,b)`関数では行ベクトルaと列ベクトルbの行列積が出力されます。

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/img1_60.png" width="500">

**ノルム** とは、ベクトルの長さを返すもので、要素の二乗値を足し合わせて、ルートを被せたものです。こちらに関しても今回は深く触れませんが、以下のように計算することができます。

`np.linalg.norm(a)`関数も同様に、ベクトルaとbのノルムが出力されます。

<img src="https://aidemyexstorage.blob.core.windows.net/aidemycontents/1522138050514683.png" width="500">

#### 問題


- 変数`arr`と`arr`の行列積を出力してください。
- 変数`vec`のノルムを出力してください。

In [ ]:
import numpy as np

# arrを定義します
arr = np.arange(9).reshape(3, 3)

# 変数arrとarrの行列積を出力してください
print()

# vecを定義します
vec = arr.reshape(9)

# 変数vecのノルムを出力してください
print()

#### ヒント

- `x.dot(y)`または`np.dot(x, y)`
- `numpy`は`np`と省略できます。

#### 解答例

In [ ]:
import numpy as np

# arrを定義します
arr = np.arange(9).reshape(3, 3)

# 変数arrとarrの行列積を出力してください
print(np.dot(arr, arr))

# vecを定義します
vec = arr.reshape(9)

# 変数vecのノルムを出力してください
print(np.linalg.norm(vec))

***

### 1.3.8 統計関数 

**統計関数とは`ndarray`配列全体、もしくは特定の軸を中心とした数学的な処理を行う関数、またはメソッド** です。既に学習した統計関数には、NumPy入門「 **axis** 」で取り扱った **配列の和を返す`sum()`関数** などがありました。

よく使われるものには、 **配列の要素の平均を返す`np.mean()`関数や`np.average()`関数** 、 **最大値・最小値を返す`np.max()`関数・`np.min()`関数** などがあります。また、 **要素の最大値、または最小値のインデックス番号を返す`np.argmax()`、`np.argmin()`** メソッドがあります。さらにこれらのメソッドは、**平均を返す`np.average()`関数**を除き、**ndarray配列に適用する`ndarray.mean()`メソッドや`ndarray.max()`メソッド**などのようにオブジェクトそのものに対するメソッドも用意されています。

他にも、統計分野でよく使われる **「標準偏差」や「分散」を返す関数として`np.std()`関数・`np.var()`関数** などがあります。「標準偏差」や「分散」の計算方法に関しては、今回は詳しく扱いませんが、これらは **データのバラつきを示す指標** です。

`sum()`関数で`axis`で指定することによりどの軸を中心に処理するかを決めることができたように、`mean()`関数・メソッドなどでも同じように軸を指定できます。`argmax()`、`argmin()`関数・メソッドの場合は、`axis`で指定された軸ごとに最大または最小値のインデックスを返します。以下のように、 **列ごとに処理を行う軸が`axis = 0`で、行ごとに処理を行う軸が`axis = 1`** となることを再度復習しましょう。

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/numpy_axis.png" width="300">


#### 問題


- 変数`arr`の列ごとの平均を出力してください。
- 変数`arr`の行の合計を出力してください。
- 変数`arr`の最小値を出力してください。
- 変数`arr`のそれぞれの列の最大値のインデックス番号を出力してください。
- 出力はprint関数を用いてください。

In [ ]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

# 変数arrの列ごとの平均を出力してください
print()

# 変数arrの行の合計を出力してください
print()

# 変数arrの最小値を出力してください
print()

# 変数arrのそれぞれの列の最大値のインデックス番号を出力してください
print()

#### ヒント

- `axis`で指定した側を計算します。

#### 解答例

In [ ]:
import numpy as np

arr = np.arange(15).reshape(3, 5)

# 変数arrの列ごとの平均を出力してください
print(arr.mean(axis=0))

# 変数arrの行の合計を出力してください
print(arr.sum(axis=1))

# 変数arrの最小値を出力してください
print(arr.min())

# 変数arrのそれぞれの列の最大値のインデックス番号を出力してください
print(arr.argmax(axis=0))

***

### 1.3.9 ブロードキャスト

サイズの違うNumPy配列(以下ndarray)同士の演算時に、 **<font color=#AA0000>ブロードキャスト</font>** という処理が自動で行われます。ブロードキャストは、 **2つのndarray同士の演算時にサイズの小さい配列の行と列を自動で大きい配列に合わせます。** 2つの配列の行が一致しないときは、行の少ない方が多い方の数に合わせ、足りない分を既存の行からコピーします。列が一致しない場合もまた然りです。どんな配列でもブロードキャストができるわけではありませんが、以下のように **全ての要素に同じ処理をする時** などはブロードキャスト可能になります。

<img src="https://aidemyexcontentspic.blob.core.windows.net/contents-pic/4000_numpy/img1_80.png" width="400">

このケースをコードで書くと、以下のようになります。
```python
x = np.arange(6).reshape(2, 3)
print(x + 1)
# 出力結果
[[1 2 3]
 [4 5 6]]
```

#### 問題


- 0から4の整数値を持つ1次元ndarray配列yを用いて、配列xの各要素から列のインデックス番号を引いてください。ただし、最初の列を0番目とします。

In [ ]:
import numpy as np


# 0から14の整数値をもつ3×5のndarray配列xを生成
x = np.arange(15).reshape(3, 5)

# 0から4の整数値をもつ1×5のndarray配列yを生成
y = np.array([np.arange(5)])

# xのn番目の列のすべての要素に対してnだけ引いてください
z = 

# xを出力
print(z)

#### ヒント

- ブロードキャストは、2つのndarray同士の演算時にサイズの小さい配列の列もしくは行を自動で大きい配列に合わせます。
- 出力結果は
```python
[[ 0  0  0  0  0]
 [ 5  5  5  5  5]
 [10 10 10 10 10]]
```
となります。

#### 解答例

In [ ]:
import numpy as np


# 0から14の整数値をもつ3×5のndarray配列xを生成
x = np.arange(15).reshape(3, 5)

# 0から4の整数値をもつ1×5のndarray配列yを生成
y = np.array([np.arange(5)])

# xのn番目の列のすべての行からnだけ引いてください
z = x - y

# xを出力
print(z)

***

## 1.3 添削問題

これまで学んできたことを用いて解いてみましょう。

#### 問題


- 各要素が`0 ~ 30`の整数の行列`（5 × 3）`を変数`arr`に代入してください。
- 変数`arr`を転置してください。
- 変数`arr`の`2, 3, 4`列のみの行列`(3 × 3)`を変数`arr1`に代入してください。
- 変数`arr1`を行でソートしてください。
- 各列の平均を出力してください。

In [ ]:
import numpy as np


np.random.seed(100)

# 各要素が0~30の整数の行列（5×3）を変数arrに代入してください

print(arr)

# 変数arrを転置してください

print(arr)

# 変数arrの2, 3, 4列のみの行列(3×3)を変数arr1に代入してください

print(arr1)

# 変数arr1を行でソートしてください

print(arr1)

# 各列の平均を出力してください




#### ヒント

- `np.random.randint()`
- `arr.T`
- `arr[:, 2:]`
- `np.sort()`ではなく`sort()`も用いてください。
- `axis`の設定に注意してください。

#### 解答例

In [ ]:
import numpy as np


np.random.seed(100)

# 各要素が0 ~ 30の整数の行列（5 × 3）を変数arrに代入してください
arr = np.random.randint(0, 31, (5, 3))
print(arr)

# 変数arrを転置してください
arr = arr.T
print(arr)

# 変数arrの2, 3, 4列のみの行列(3 × 3)を変数arr1に代入してください
arr1 = arr[:, 1:4]
print(arr1)

# 変数arr1を行でソートしてください
arr1.sort(1)
print(arr1)

# 各列の平均を出力してください
print(arr1.mean(axis = 0))


- 乱数を発生させる`np.random.randint(x, y, z)`は、`x ~ y-1`の整数値を`z`個生成します。`0 ~ 30`まで発生させるには、`np.random.randint(0, 31, 個数)`と指定します。
- スライス機能を使って一部を取り出し、`mean()`を用いて平均を計算します。平均を求める軸を設計するための`axis=0`を設定します。

***