# 総合添削問題

総合添削問題では、numpyの知識を用いて2枚の画像の差分を計算して求めてみましょう。問題を簡単にするため、0~5のいずれかの整数を色とみなします。画像は二次元データであるため行列として表すことができ、Numpy配列として扱うことが可能です。サイズが等しい画像の差分は、同じ位置の要素同士の差を成分とする行列で表され、これを画像とみなすことができます。

#### 問題

- 乱数を用いて指定の大きさの画像を生成する関数`make_image()`を完成させてください。
- 渡された行列のうちの一部を乱数を用いて変更する関数`change_matrix()`を完成させてください。
- 生成した`image1`と`image2`の各要素の差分の絶対値を計算し、`image3`に代入してください。

In [115]:
import numpy as np
import time
# 乱数の初期化
np.random.seed(int(time.time()))

# 縦の大きさ、横の大きさを渡されたときに乱数で指定の大きさの画像を生成する関数
def make_image(m, n):
    # n×m行列の各成分を0~5の値でランダムに満たしてください
    image = np.random.randint(0, 5+1, (m, n))
#    image = np.array(np.random.rand(m, n))
#    for i in range(m):
#        image[i] = np.random.randint(0, 5+1, n)
    
    return image


# 渡された行列の一部を変更する関数
def change_matrix(matrix):
    
    # 与えられた行列の形を取得し、shapeに代入してください
    shape = np.shape(matrix)
    
    # 行列の各成分について、変更するかしないかをランダムに決めた上で
    changes = np.random.rand(shape[0], shape[1]) 
    threshold = 0.5    

    for i in range(shape[0]):
        for j in range(shape[1]):
            # 変更する場合は0~5のいずれかの整数にランダムに入れ替えてください
            if  changes[i][j] > threshold:
                matrix[i][j] = np.random.randint(0, 5+1)
    
    return matrix

# ランダムに画像を作成
print("image1 - original")
image1 = make_image(3, 3)
print(image1)

# ランダムに変更を適用する
print("image2 - random")
image2 = change_matrix(np.copy(image1))
print(image2)

# image1とimage2の差分を計算し、image3に代入してください
image3 = image1 - image2
print("image3 - diff")

# image3を出力
print(image3)
image3 = np.abs(image3)
print("image3 - diff - abs")
print(image3)

image1 - original
[[5 2 2]
 [5 1 0]
 [5 2 2]]
image2 - random
[[1 2 2]
 [5 2 5]
 [5 0 0]]
image3 - diff
[[ 4  0  0]
 [ 0 -1 -5]
 [ 0  2  2]]
image3 - diff - abs
[[4 0 0]
 [0 1 5]
 [0 2 2]]


#### ヒント

- 同じ形のNumpy配列どうしの足し算や引き算は同じ位置の要素同士で計算されます。
- `numpy.random.randint(x, y, z)`で`x　~　y-1`までの範囲の整数をランダムに`z`個得ることができます。

###  解答例

###  解説

添削課題の提出は以下のアドレスから提出いただきますようお願いします。<br>

https://goo.gl/forms/fW7CAspZMwHuWuqk2<br><br>
以下のアドレスからアンケートにご協力頂きたく存じます。<br>
ご回答のほど、よろしくお願いいたします。

https://goo.gl/forms/WHjJQYeodIndRvyz2